export const QuizData = [
  {
    id: 0,
    question: `What is the capital of Nigeria?`,
    options: [`New Delhi`, `Abuja`, `Owerri`, `Enugu`],
    answer: `Abuja`,
  },
  {
    id: 1,
    question: `What is the capital of India?`,
    options: [`New Delhi`, `Abuja`, `Mumbai`, `Aba`],
    answer: `New Delhi`,
  },
  {
    id: 2,
    question: `What is the capital of Australia?`,
    options: [`Melbourne`, `Akokwa`, `Owerri`, `Sydney`],
    answer: `Sydney`,
  },
  {
    id: 3,
    question: `What is the capital of Turkey?`,
    options: [`Rijadh`, `Ankara`, `Istanbul`, `Abakaliki`],
    answer: `Ankara`,
  },
  {
    id: 4,
    question: `What is the capital of Syria?`,
    options: [`Syria`, `Damascus`, `Anambra`, `Enugu`],
    answer: `Damascus`,
  },
  {
    id: 5,
    question: `What is the capital of France?`,
    options: [`Paris`, `Berlin`, `Rome`, `Madrid`],
    answer: `Paris`,
  },
  {
    id: 6,
    question: `Which planet is known as the Red Planet?`,
    options: [`Earth`, `Mars`, `Venus`, `Jupiter`],
    answer: `Mars`,
  },
  {
    id: 7,
    question: `In which year did World War II end?`,
    options: [`1939`, `1945`, `1950`, `1960`],
    answer: `1945`,
  },
  {
    id: 8,
    question: `What is the largest mammal on Earth?`,
    options: [`Elephant`, `Blue Whale`, `Giraffe`, `Gorilla`],
    answer: `Blue Whale`,
  },
  {
    id: 9,
    question: `Which programming language is often used for building web applications?`,
    options: [`Python`, `JavaScript`, `Java`, `C++`],
    answer: `JavaScript`,
  },
  {
    id: 10,
    question: `Which programming language is often used for building Industrial Automation?`,
    options: [`Python`, `JavaScript`, `LadderLogic`, `C++`],
    answer: `LadderLogic`,
  },
  {
    id: 11,
    question: `What is the largest planet in our solar system?`,
    options: [`Venus`, `Jupiter`, `Mars`, `Saturn`],
    answer: `Jupiter`,
  },
  {
    id: 12,
    question: `Which element has the chemical symbol 'O'?`,
    options: [`Osmium`, `Oxygen`, `Oganesson`, `Olivine`],
    answer: `Oxygen`,
  },
  {
    id: 13,
    question: `What is the capital of Australia?`,
    options: [`Sydney`, `Melbourne`, `Canberra`, `Brisbane`],
    answer: `Canberra`,
  },
  {
    id: 14,
    question: `In which year did World War II end?`,
    options: [`1943`, `1945`, `1947`, `1950`],
    answer: `1945`,
  },
  {
    id: 15,
    question: `Who wrote the play 'Romeo and Juliet'?`,
    options: [`Charles Dickens`, `William Shakespeare`, `Jane Austen`, `Homer`],
    answer: `William Shakespeare`,
  },
  {
    id: 16,
    question: `Which planet is known as the Red Planet?`,
    options: [`Venus`, `Mars`, `Jupiter`, `Mercury`],
    answer: `Mars`,
  },
  {
    id: 17,
    question: `What is the currency of Japan?`,
    options: [`Yen`, `Won`, `Ringgit`, `Baht`],
    answer: `Yen`,
  },
  {
    id: 18,
    question: `Who is the author of 'To Kill a Mockingbird'?`,
    options: [
      `Harper Lee`,
      `J.K. Rowling`,
      `Ernest Hemingway`,
      `George Orwell`,
    ],
    answer: `Harper Lee`,
  },
  {
    id: 19,
    question: `Which is the smallest prime number?`,
    options: [`0`, `1`, `2`, `3`],
    answer: `2`,
  },
];
